language: c
cache: ccache
compiler: gcc
sudo: true
git:
  depth: 1
  submodules: true
  
before_script:
    - sudo apt-get -qq update >/dev/null
    - sudo apt-get -qq install --force-yes binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686 p7zip-full gcc-multilib libx11-dev:i386 libxext-dev:i386 x11-utils libgl1-mesa-dev libasound-dev zlib1g:i386 libstdc++6:i386 >/dev/null
    - jdk_switcher use oraclejdk8
    - curl -s http://dl.google.com/android/android-sdk_r22.0.4-linux.tgz | tar xzf -
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:$PWD/android-ndk
    - sleep 3s; echo y | android update sdk -u --filter platform-tools,build-tools-19.0.0,android-19 --force --all > /dev/null
    - wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin >/dev/null 2>/dev/null
    - 7z x ./android-ndk-r10e-linux-x86_64.bin > /dev/null
    - mv android-ndk-r10e android-ndk
    - curl -s http://libsdl.org/release/SDL2-devel-2.0.6-mingw.tar.gz | tar xzf -
    - mv SDL2-2.0.6 sdl2-mingw
    - curl -s http://libsdl.org/release/SDL2-2.0.6.tar.gz | tar xzf -
    - git clone --depth 1 https://github.com/FWGS/vgui-dev
    - git clone --depth 1 https://github.com/FWGS/vgui_support_bin
    - git clone --depth 1 https://github.com/FWGS/xash3d-android-project
script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/build_android_engine.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/build_mingw_engine.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/build_portable_linux_engine.sh; fi
after_script:
    - cd ${TRAVIS_BUILD_DIR}
    - ccache --show-stats > ccache_stats.log
    - sh scripts/travis-deploy.sh travis xash3d-mingw.7z xash3d-linux.7z xash3d-generic.apk android-debug-symbols.txz ccache_stats.log
    - sh scripts/travis-upload.sh xash3d-mingw.7z xash3d-linux.7z xash3d-generic.apk
